%% plotTDKCharField
% Explore TDK TAS2141 characterization field.
%
%% Syntax
%   fig = plotTDKCharField()
%
%
%% Description
% fig = plotTDKCharField() explore characterization field of TDK sensor.
%
%
%% Examples
%   figs = plotTDKCharField();
%
%
%% Input Arguments
% *None*
%
%
%% Output Arguments
% *fig* created figure handle.
%
%
%% Requirements
% * Other m-files: none
% * Subfunctions: none
% * MAT-files required: data/TDK_TAS2141_Characterization_2019-07-24.mat,
%   data/config.mat
%
%
%% See Also
% * <plotTDKCharDataset.html plotTDKCharDataset>
%
%
% Created on October 28. 2020 by Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on Month DD. YYYY by Editor: Single line description.
% -->
% </html>
%
function [Figures] = plotTDKCharField()
    try
        % load dataset path and dataset content into function workspace
        load('config.mat', 'PathVariables');
        load(PathVariables.tdkDatasetPath, 'Data', 'Info');
        close all;
    catch ME
        rethrow(ME)
    end
    
    % figure save path for different formats %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    figFilename = "tdk_%s_stimulus";
    figPath = fullfile(PathVariables.saveFiguresPath, figFilename);
    
    
    % load needed data from dataset in to local variables for better handling %%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % get from user which field to investigate
    fields = Info.SensorOutput.CosinusBridge.Determination;
    nFields = length(fields);
    fprintf('Choose 1 of %d fields ...\n', nFields);
    for i = 1:nFields
        fprintf('%s\t:\t(%d)\n', fields{i}, i);
    end
    
    % load characterization data
    iField = input('Choice: ');
    field = fields{iField};
    Vcos = Data.SensorOutput.CosinusBridge.(field);
    Vsin = Data.SensorOutput.SinusBridge.(field);
    
    % get unit strings from
    kApm = Info.Units.MagneticFieldStrength;
    Hz = Info.Units.Frequency;
    mV = Info.Units.SensorOutputVoltage;
    
    % get dataset infos and format strings to place in figures
    % subtitle string for all figures
    infoStr = join([Info.SensorManufacturer, Info.Sensor, Info.SensorTechnology, ...
        Info.SensorType, "Sensor Characterization Dataset."]);
    dateStr = join(["Created on", Info.Created, "by", 'Thorben Sch\"uthe', ...
        "and updated on", Info.Edited, "by", Info.Editor + "."]);
    
    % clear dataset all loaded
    clear Data Info;
        
    % create figure for plots %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    fig1 = figure('Name', 'Char Field', ...
        'NumberTitle' , 'off', ...
        'WindowStyle', 'normal', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Units', 'centimeters', ...
        'OuterPosition', [0 0 30 30], ...
        'PaperType', 'a4', ...
        'PaperUnits', 'centimeters', ...
        'PaperOrientation', 'landscape', ...
        'PaperPositionMode', 'auto', ...
        'DoubleBuffer', 'on', ...
        'RendererMode', 'manual', ...
        'Renderer', 'painters');
    
    tdl = tiledlayout(fig1, 2, 2, ...
        'Padding', 'normal', ...
        'TileSpacing' , 'compact');
    
    title(tdl, sprintf('Characterization Field: %s', field), ...
        'FontWeight', 'normal', ...
        'FontSize', 18, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    subtitle(tdl, [infoStr; dateStr], ...
        'FontWeight', 'normal', ...
        'FontSize', 14, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    
    % Hx stimulus
    nexttile;
    p = plot(phi, Hmag, phi, -Hmag, phi(idxR), Hx(idxR), phi(idxF), Hx(idxF));
    set(p, {'Color'}, {'k', 'k', 'b', 'r'}');
    legend([p(1) p(3) p(4)], {'mod', 'rise', 'fall'},...
        'FontWeight', 'normal', ...
        'FontSize', 9, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex', ...
        'Location', 'NorthEast');
        
    xticks((0:0.25*pi:2*pi) * nPeriods);
    xticklabels({'0', '8\pi', '16\pi', '24\pi', '32\pi', '40\pi', '48\pi', '56\pi', '64\pi'});
    xlim([0 phi(end)]);
    ylim([Hmin Hmax]);
    
    xlabel('$\phi$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_x(\phi)$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title(sprintf('Modulation $f_m = %1.2f$ %s, Cos-Carrier $f_c = %1.2f$ %s', fm, Hz, fc, Hz), ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % Hy stimulus
    nexttile;
    p = plot(phi, Hmag, phi, -Hmag, phi(idxR), Hy(idxR), phi(idxF), Hy(idxF));
    set(p, {'Color'}, {'k', 'k', 'b', 'r'}');
    legend([p(1) p(3) p(4)], {'mod', 'rise', 'fall'},...
        'FontWeight', 'normal', ...
        'FontSize', 9, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex', ...
        'Location', 'NorthEast');
        
    xticks((0:0.25*pi:2*pi) * nPeriods);
    xticklabels({'0', '8\pi', '16\pi', '24\pi', '32\pi', '40\pi', '48\pi', '56\pi', '64\pi'});
    xlim([0 phi(end)]);
    ylim([Hmin Hmax]);
    
    xlabel('$\phi$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y(\phi)$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title(sprintf('Modulation $f_m = %1.2f$ %s, Sin-Carrier $f_c = %1.2f$ %s', fm, Hz, fc, Hz), ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % polar for rising modulation
    nexttile;
    polarplot(phi(idxR), Hmag(idxR), 'b');
    title('$|H(\phi)| \cdot e^{-j\phi}$ f. $0 \le \phi \le 32\pi$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % polar for rising modulation
    nexttile;
    polarplot(phi(idxF), Hmag(idxF), 'r');
    title('$|H(\phi)| \cdot e^{-j\phi}$ f. $32\pi \le \phi \le 64\pi$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % save results of figure 1
    savefig(fig1, figPath);
    print(fig1, fig1SvgPath, '-dsvg');
    print(fig1, fig1EpsPath, '-depsc', '-tiff', '-loose');
    print(fig1, fig1PdfPath, '-dpdf', '-loose', '-fillpage');
    
    % figure 2 cosinus bridge outputs
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    fig2 = figure('Name', 'Cosinus Bridge', ...
        'NumberTitle' , 'off', ...
        'WindowStyle', 'normal', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Units', 'centimeters', ...
        'OuterPosition', [0.0 0.0 30.0 30.0], ...
        'PaperType', 'a4', ...
        'PaperUnits', 'centimeters', ...
        'PaperOrientation', 'landscape', ...
        'PaperPositionMode', 'auto', ...
        'DoubleBuffer', 'on', ...
        'RendererMode', 'manual', ...
        'Renderer', 'painters');
    
    tdl = tiledlayout(fig2, 2, 2, ...
        'Padding', 'normal', ...
        'TileSpacing' , 'compact');
    
    title(tdl, 'Measured Cosinus Bridge Outputs of Corresponding $H_x$-/ $H_y$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 18, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    subtitle(tdl, [infoStr; dateStr], ...
        'FontWeight', 'normal', ...
        'FontSize', 14, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    xlabel(tdl, sprintf('$H_x$, $H_y$ in %s, %d Steps in %.4f %s', kApm, Hsteps, Hres, kApm), ...
        'FontWeight', 'normal', ...
        'FontSize', 16, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
        
    colormap('jet');
    
    % cosinus bridge recorded during rising stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vcos.Rise);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~isnan(Vcos.Rise));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Rising $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % cosinus bridge recorded during falling stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vcos.Fall);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~isnan(Vcos.Fall));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Falling $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');

    % cosinus bridge recorded during superimposed stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vcos.All);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~(~Vcos.All));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Superimposed $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % cosinus bridge recorded during differentiated stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vcos.Diff);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~isnan(Vcos.Diff));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Differentiated $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
      
    % add colorbar and place it overall plots
    cb = colorbar;
    cb.Layout.Tile = 'east';
    cb.Label.String = sprintf('$V_{cos}(H_x, H_y)$ in %s', mV);
    cb.Label.Interpreter = 'latex';
    cb.Label.FontSize = 16;
    
    % save results of figure 2
    savefig(fig2, fig2Path);
    print(fig2, fig2SvgPath, '-dsvg');
    print(fig2, fig2EpsPath, '-depsc', '-tiff', '-loose');
    print(fig2, fig2PdfPath, '-dpdf', '-loose', '-fillpage');
    
    
    % figure 3 sinus bridge outputs
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    fig3 = figure('Name', 'Sinus Bridge', ...
        'NumberTitle' , 'off', ...
        'WindowStyle', 'normal', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Units', 'centimeters', ...
        'OuterPosition', [0.0 0.0 30.0 30.0], ...
        'PaperType', 'a4', ...
        'PaperUnits', 'centimeters', ...
        'PaperOrientation', 'landscape', ...
        'PaperPositionMode', 'auto', ...
        'DoubleBuffer', 'on', ...
        'RendererMode', 'manual', ...
        'Renderer', 'painters');
    
    tdl = tiledlayout(fig3, 2, 2, ...
        'Padding', 'normal', ...
        'TileSpacing' , 'compact');
    
    title(tdl, 'Measured Sinus Bridge Outputs of Corresponding $H_x$-/ $H_y$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 18, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    subtitle(tdl, [infoStr; dateStr], ...
        'FontWeight', 'normal', ...
        'FontSize', 14, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    xlabel(tdl, sprintf('$H_x$, $H_y$ in %s, %d Steps in %.4f %s', kApm, Hsteps, Hres, kApm), ...
        'FontWeight', 'normal', ...
        'FontSize', 16, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
        
    colormap('jet');
    
    % sinus bridge recorded during rising stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vsin.Rise);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~isnan(Vsin.Rise));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Rising $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % sinus bridge recorded during falling stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vsin.Fall);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~isnan(Vsin.Fall));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Falling $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');

    % sinus bridge recorded during superimposed stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vsin.All);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~(~Vsin.All));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Superimposed $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    % sinus bridge recorded during differentiated stimulus 
    nexttile;
    im = imagesc([Hmin Hmax], [Hmin Hmax], Vsin.Diff);
    set(gca, 'YDir', 'normal');
    set(im, 'AlphaData', ~isnan(Vsin.Diff));
    caxis([Vmin, Vmax]);
    xlim([Hmin Hmax]);
    ylim([Hmin Hmax]);
    yticks(xticks);
    axis square xy;
    grid on;
    
    xlabel('$H_x$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    ylabel('$H_y$', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
    
    title('Differentiated $H$-Amplitudes', ...
        'FontWeight', 'normal', ...
        'FontSize', 12, ...
        'FontName', 'Times', ...
        'Interpreter', 'latex');
      
    % add colorbar and place it overall plots
    cb = colorbar;
    cb.Layout.Tile = 'east';
    cb.Label.String = sprintf('$V_{sin}(H_x, H_y)$ in %s', mV);
    cb.Label.Interpreter = 'latex';
    cb.Label.FontSize = 16;
    
    % save results of figure 3
    savefig(fig3, fig3Path);
    print(fig3, fig3SvgPath, '-dsvg');
    print(fig3, fig3EpsPath, '-depsc', '-tiff', '-loose');
    print(fig3, fig3PdfPath, '-dpdf', '-loose', '-fillpage');
    
    % return figure handles as struct
    Figures = struct('fig1', fig1, 'fig2', fig2, 'fig3', fig3);
end
