%% computeDipoleH0Norm
% Compute the norm factor for magnetic field generated by an Dipole in its zero
% position. That means the maximum H-field magnitude in zero position with no
% position shifts in x or y direction. So that norm factor is related to the
% center point of the coordinate system in x and y direction and to the dipoles
% initial z position. Which can be seen as sphere magnet for far field of the
% sphere. The norm relates that a dipole magnet in center of a sphere with a
% radius has certain field strength in related distance. For example a sphere of
% 2 mm radius has in 5 mm distance a field strength of 200 kA/m
%
% It is simplified computation for the dipole equation for one position in
% inital state without tilt in z-axes tor bring on a free choosen field strength
% to define the magnet. Because far field of sphere can be seen as dipole.
%
% $$\vec{H_0}(\vec{r_0}) = \frac{1}{4\pi} \cdot \Biggl(
% \frac{3\vec{r_0}\left(\vec{m_0}^T\vec{r_0}\right)}{|\vec{r_0}|^5} - 
% \frac{\vec{m_0}}{|\vec{r_0}|^3}\Biggr)$$
% 
% $$H_{0norm} = \frac{H_{mag}}{|H_0(r_0)|}$$
%   
%% Syntax
%   H0norm = computeDipoleH0Norm(Hmag, m0, r0)
%
%
%% Description
% *H0norm = computeDipoleH0Norm(Hmag, m0, r0)* computes scalar norm factor related
% to dipole rest position. Multiply that factor to dipole generated fields which
% are computed with the same magnetic moment magnitude to imprint a choosen
% magnetic field strength magnitude on the dipole field rotation.
%
%
%% Examples
%   % distance where the magnetic field strength is the value of wished
%   % magnitude, in mm
%   r0 = [0; 0; -5]
%   % field strength to imprint in norm factor in kA/m
%   Hmag = 200
%   % magnetic moment magnitude which is used generate rotation moments
%   m0 = [-1e6; 0; 0]
%   % compute norm factor for dipole rest position
%   H0norm = computeDipoleH0Norm(Hmag, m0, r0)
%
%
%% Input Argurments
% *Hmag* real scalar of H-field strength magnitude to imprint in norm factor to
% define a dipole sphere with constant radius and field strength at this radius.
%
% *m0* vector of magnetic moment magnitude which must be same as for later
% rotation of the dipole.
%
% *r0* vector of distance in rest position of magnet center.
%
%
%% Output Argurments
% *H0norm* real scalar of norm factor which relates to the zero position of the
% dipole sphere and can be multiplied to generated dipole H-field to imprint a
% magnetic field strength relative to the position of sensor array. The
% imprinted field strength magnitude relates to the rest position z0 + rsp.
%
%
%% Requirements
% * Other m-files required: None
% * Subfunctions: None
% * MAT-files required: None
%
%
%% See Also
% * <rotate3DVector.html rotate3DVector>
% * <generateDipoleRotationMoments.html generateDipoleRotationMoments>
% * <https://en.wikipedia.org/wiki/Magnetic_dipole Wikipedia Magnetic Dipole>
%
%
% Created on November 11. 2020 by Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on Month DD. YYYY by Editor: Single line description.
% -->
% </html>
%
function [H0norm] = computeDipoleH0Norm(Hmag, m0, r0)
    arguments
        % validate inputs as real scalars
        Hmag (1,1) double {mustBeReal}
        m0 (3,1) double {mustBeReal, mustBeVector}
        r0 (3,1) double {mustBeReal, mustBeVector}
    end
    
    % calculate the magnitude of all positions
    r0abs = sqrt(sum(r0.^2, 1));
    
    % calculate the the unit vector of all positions
    r0hat = r0 ./ r0abs;
    
    % calculate field strength and magnitude at position
    H0 = (3 * r0hat .* (m0' * r0hat) - m0) ./ (4 * pi *r0abs.^3);
    H0abs = sqrt(sum(H0.^2, 1));
    
    % compute the norm factor like described in the equations
    H0norm = Hmag / H0abs;
end

