%% computeDipoleH0Norm
% Compute the norm factor for magnetic field generated by an Dipole in its zero
% position. That means the maximum H-field magnitude in zero position with no
% position shifts in x or y direction. So that norm factor is related to the
% center point of coordinate system in x and y direction and to the dipoles
% initial z position. Which can be a sphere radius in example or just its rest
% position.
%
% It is simplified computation for the dipole equation for one position in
% inital state without tilt in z-axes tor bring on a free choosen field strength
% to define the magnet.
%
% $$\vec{H_0}(\vec{r_0}) = \frac{1}{4\pi} \cdot \Biggl(
% \frac{3\vec{r_0}\left(\vec{m_0}^T\vec{r_0}\right)}{|\vec{r_0}|^5} - 
% \frac{\vec{m_0}}{|\vec{r_0}|^3}\Biggr)$$
% 
% For rest position without any tilt it is choosen to set the magnetic moment in
% negative x direction although y direction would be fine. Because of there is
% not tilt there is no z component in the moment vector so the vector. The
% dipole position has no x and y components only z and so the half of equation
% is set to zero.
%
% $$\vec{m_0} = \left[\matrix{-m_0 \cr 0 \cr 0}\right] \quad 
%   \vec{r_0} = \left[\matrix{0 \cr 0 \cr z_0'}\right]$$
%
% $$|\vec{r_0}| = z_0' = |-(z_0 + r_{sp})| = |r_{sp}| \quad z_0 = 0$$
% 
% $$|\vec{m_0}| = |m_0|$$
%
% So on the H-field for the rest position is only related to z in the rest
% position and the magnitude of the rest or start momnent without tilt.
%
% $$|H_0(r_{sp})| = |H_0(z_0')| = |\vec{H_0}(\vec{r_0})| = \frac{|m_0|}{4\pi |r_{sp}|^3}$$
%
% The norming to a free choosen field strength magnitude which shall define the
% dipole magnet from rest to position to relative positions results in
%
% $$H_{0norm} = \frac{H_{mag}}{|H_0(r_{sp})|} = 4\pi |r_{sp}|^3 \cdot \frac{H_{mag}}{|m_0|}$$
%   
%% Syntax
%   H0norm = functionName(Hmag, m0, r0)
%
%
%% Description
% *H0norm = functionName(Hmag, m0, r)* compute scalar norm factor related to
% dipole rest position. Multiply that factor to dipole generated fields which
% are computed with the same magnetic moment magnitude to imprint a choosen
% magnetic field strength magnitude on the dipole field rotation.
%
%
%% Examples
%   % position of the sensor array in z direction an mm should be zero
%   z0 = 0
%   % radius of dipoles sphere in mm
%   rsp = 2
%   % rest position of the dipole
%   r0 = -(z0 + rsp)
%   % field strength to imprint in norm factor in kA/m
%   Hmag = 8.5
%   % magnetic moment magnitude which is used generate rotation moments
%   Mmag = 1e6
%   % compute norm factor for dipole rest position
%   H0norm = computeDipoleH0Norm(Hmag, Mmag, r0)
%
%
%% Input Argurments
% *Hmag* real scalar of H-field strength magnitude to imprint in norm factor to
% define a dipole sphere with constant radius and field strength at this radius.
%
% *m0* real scalar of magnetic moment magnitude which must be same as for later
% roatition of the dipole.
%
% *r* real scalar of dipole sphere radius on which a constant field strength has
% its effect.
%
%
%% Output Argurments
% *H0norm* real scalar of norm factor which relates to the zero position of the
% dipole sphere and can be multiplied to generated dipole H-field to imprint a
% magnetic field strength relative to the position of sensor array.
%
%
%% Requirements
% * Other m-files required: None
% * Subfunctions: None
% * MAT-files required: None
%
%
%% See Also
% * <rotate3DVector.html rotate3DVector>
% * <generateDipoleRotationMoments.html generateDipoleRotationMoments>
% * <https://en.wikipedia.org/wiki/Magnetic_dipole Wikipedia Magnetic Dipole>
%
%
% Created on November 11. 2020 by Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on Month DD. YYYY by Editor: Single line description.
% -->
% </html>
%
function [H0norm] = computeDipoleH0Norm(Hmag, m0, r)
    arguments
        % validate inputs as real scalars
        Hmag (1,1) double {mustBeReal}
        m0 (1,1) double {mustBeReal}
        r (1,1) double {mustBeReal}
    end
    
    % compute the norm factor like described in the equations
    H0norm = 4 * pi * abs(r)^3 * Hmag / abs(m0);
end

