%% Config Mat
% The configuration mat-file is a script generated mat-file. Generated by
% generateConfigMat script. The mat-files contains program and software wide
% useful configuration like path variables or parameter settings for program
% tasks or functions. It centralizes the program controlling configuration at
% once and can be full or partial loaded at different program stages. The key
% point is the configuration can only be modified by the generating script so
% that the config values are truly constant. Varaition should be saved to temp
% folder or a temp mat-file. The configuration should be generated after major
% changes to the program or an established regeneration flow at program startup.
% The config.mat file is located under data directory and to path variable. Just
% load in to the needed workspace.
%
%   load('config.mat')
%
%
%% Requirements
% * Other m-files scripts/generateConfigMat
% * Subfunctions: None
% * MAT-files required: None
%
%
%% See Also
% * <generateConfigMat.html generateConfigMat>
%
%
% Created on October 31. 2020 by Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on Month DD. YYYY by Editor: Single line description.
% -->
% </html>
%
