%% Project Structure
% A good project directory structure is the key to build scalable and expandable
% software projects. Therfore each project folder has to fulfill an associated
% task. Additionally, a good structure facilitates project navigation and the
% retrieval and reuse of project content. Further on Matlab provides stratgies
% to add content to existing project structures and label it for script based
% execution of project task to manage project files. To add new content have a
% look at the links below.
%
%
%% See Also
% * <matlab:web(fullfile(docroot,'simulink/ug/specify-project-path.html')) Specify Project Path>
% * <matlab:web(fullfile(docroot,'simulink/ug/add-files-to-the-project.html')) Add Files to the Project>
% * <matlab:web(fullfile(docroot,'simulink/ug/add-labels-to-files.html')) Add Labels to Files>
%
%
%% Directory Tasks
%
% *Directory* Task.
%
% *./* Main project directory which contains the Matlab project sandbox files
% and the hidden repository files. Matlab project sandbox directory.
% Project root directory which contains the Matlab project file, 
% the info.xml, .gitignore, .gitattributes files and all other project
% related subdirectories. Startup directory.
%
% *./.git* Hidden repository for local standalone work. Saves daily
% working results. Provide a Git clonable instance of sandbox the directory.
% Replacable. Not Matlab driven, simulates remote repository.
% 
% *./resources* Autogenerated directory from Matlab project. Contains the local
% project versioning and project xml-files.
% 
% *./data* Contains all project related datasets e.g. mat-files.
% 
% *./data/trainig* Contains mat-files from sensor array simulation for training
% cases of the gaussian process.
%
% *./data/test* Contains mat-files from sensor array simulation for test
% cases of the gaussian process.
%
% *./docs* Documentation directory which contains m-files only for documentation
% use and the directory where all project remarked files are published into
% HTML output files.
% 
% *./docs/html* Publish directory where published m-files are collected and
% bind to a Matlab help browser readable documentation. It contains html-files
% and subdirectory for images and figures which are used in the documentaion.
% The help browser search database is placed here too. Much more important
% the directory contains the helptoc.xml which pointed by the info.xml from
% root project directory.
%
% *./docs/html/helpsearch* Contains autogenerated help search database entries.
% The directory is rewritten during the publish documentation process.
% 
% *./docs/html/images* Contains all needed image files like png-files which are
% used in the documentation (HTML).
%
% *./docs/latex* Documentation directory which LaTeX documentation of the
% project including subfolders for Thesis of each project participant.
%
% *./docs/latex/BA_Thesis_Tobias_Wulf* Bachelor Thesis directory of Tobias Wulf.
%
% *./docs/latex/Manual* Export directory for documentation written in Matlab as
% pdf export.
%
% *./scripts* The sripts directory contains all executable script m-files
% to solve certain tasks in the project, to generate datasets or execute parts
% of the toolbox source code.
%
% *./src* Source code directory which contains reusable source code clustered in
% submodule directories. The code can be function oriented or class oriented
% or a mix of both. Contains no bare script files.
%
% *./src/sensorArraySimulation* Sensor Array Simulation function and class.
% Contains functions, mathematical functions and classes to simulate an 
% N x N sensor array on base of the TDK TAS2141 characterization dataset.
%
% *./src/gaussianProcessRegression* Gaussian Process Regression module which
% contains basic math functions and submodules to implement GPR models with
% different kernels using same regression and optimization process.
%
% *./src/gaussianProcessRegression/basicMathFunctions* Basic math functions to
% perform GPR angular predictions.
%
% *./src/gaussianProcessRegression/kernelQFC* Exact Quadratic Fractional
% Covariance kernel functions which bases on matrice training data.
%
% *./src/gaussianProcessRegression/kernelQFCAPX* Approximated Quadratic
% Fractional Covariance kernel functions which bases on vector training data and
% uses norm scalar presentation of input matrix data. Using triangle inequation
% to norm matrix data before compute the covariances.
%
% *./src/util* Util function and class space. Function and class source code to
% solve upcoming help tasks e.g. to manage project content, to support plot
% framework or reporting or publishing processes.
%
% *./src/util/plotFunctions* Contains plot functions for reuse.
%
% *./tests* For test driven development each function or class needs a own
% test space or file. The directory contains these tests.
%
% *./temp* Temporally working directory to save intermediate results or the last
% software state from session before or scratch files which flies arround.
% Either made pre investigasition and supported work basics are saved here.
%
%
%% Add New Elements
%
% *Add new folder to project:*
%
% # Create a new folder and add to Project Path after Matlab flow.
% # Run Checks *>* Add Files.
% # Run tree command from shell to update directory for the documentation
%   (optional).
% # Update directorry task table of this document.
%
%
% *Add new file to project:*
%
% # Create new File and edit the file after Documentation Workflow.
%   and Conventions.
% # Run Checks *>* Add Files.
% # Label the new file from project pane.
% # Commit file into active branch.
% # Registrate to the documentation if needed (publish, toc and listings docs).
%
%
% Created on October 10. 2020 by Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on Month DD. YYYY by Editor: Single line description.
% Edited on October 07. 2020 by Tobias Wulf: Add inital description.
% Edited on October 08. 2020 by Tobias Wulf: Add workflow and overview.
% Edited on November 04. 2020 by Tobias Wulf: Add sensorArraySimulation to src.
% Edited on November 24. 2020 by Tobias Wulf: Add folders for training and test data
% -->
% </html>
%
