%% Source Code
% The project source code is clustered in modules where every subdirectory
% represents one certain module. Each module gathers functions and classes which
% are related to module specific themes or task fields. So the basic structured
% source code is located here. The combination of module functionality takes
% place in executable area of the project. So use the functions and classes in
% scripts and further on compiled binaries. Do not write bare executable source
% code here. For reproducible results and source code tracebility each module
% has its own documentation entry where all underlaying functions and classses
% are listed. The best practice to develop new source code or modules is to do
% it in test driven way. This means write a test m-file for every new function
% or class m-file and test the functionality of the source code with assertion.
% This test driven development is called unittest and provides in combination
% with detailed documentation a high percentage of reusable source code.
%
%
%% sensorArraySimulation
% Function space to solve sensor array simulation with a certain magnetic
% stimulus. The Array simulation is based on the TDK TAS2141 characterization
% dataset. A magnetic dipole is used as basic magnetic stimulus and moved as
% imaginary sphere magnet with a certain radius. The magnet rotates in
% z-direction counterclockwise.
%
%
%% gaussianProcessRegression
% Source code establish a struct based regression model which has the abillity
% to work with datasets generated by sensorArraySimulation module. Generated
% regression models and datasets can be passed to prediction functions and loss
% computation as arguments. So it is possible to build up multi model evaluation
% in scripts at a time.
%
%
%% util
% Util function and classes to provide reuse for often upcommings tasks and
% functionality besides project kernel and module source code. Located are
% plot functions and file operations.
%
%
% Created on October 10. 2020 by Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on October 10. 2020 by Tobias Wulf: Add util module.
% Edited on November 04. 2020 by Tobias Wulf: Add sensorArraySimulation to src.
% -->
% </html>
%
