%% TDK TAS2141 Characterization
% TDK characterization as base of the sensor array simulation was done before
% the dataset is just modified in its structure and not in its values. An
% additional info struct is added which contains information about how the
% dataset was aquirred and a data struct which contains the magnetic field
% resolution and the cosinus and sinus bridge images for variable Hx and Hy
% fieldstrengths. The raw dataset was aquirred after the method Thorben Schüthe
% describe in his IEEE paper for two-dimensional characterization of TMR angular
% sensors. The sensor characterized for both bridges a cosinus and sinus
% bridge. The bridges have a phisically phase shift of 90° so the sensor as able
% to reference a superimposed magnetic field flud in x- and y-direction. The
% field was generated by an cross coil setup.
%
%
%% See Also
% * <https://ieeexplore.ieee.org/document/8706125 Two-Dimensional Characterization and Simplified Simulation Procedure for Tunnel Magnetoresistive Angle Sensors>
%
%
% Created on October 27. 2020 Tobias Wulf. Copyright Tobias Wulf 2020.
%
% <html>
% <!--
% Hidden Clutter.
% Edited on Month DD. YYYY by Editor: Single line description.
% -->
% </html>
%
%
%% Magnetic Stimulus
% The right stimulus is the keynote for characterization records. It needs to
% have the abillity record slow enough for quasi static recordings but is not
% allowed to be real static so the magnetic field is not interrupted during the
% recording. Therefore slow sinoid carrier functions with even slower amplitude
% modulation is choosen to provide a quasi static stimulus. 
%
% The carrier function for the Hx-field stimulus is related to the cosinus
% bridge and so:
%
% $c_1(t) = cos(\phi(t))$
%
% Due to the physically phase shift the Hy-field stimulus is related to sinus:
%
% $c_2(t) = sin(\phi(t))$
%
% Both carrier runs with same carrier frequency:
%
% $f_c = 3.2 Hz$
%
% so they are executed with the phase vector over time:
%
% $\phi(t) = 2\pi f_c t$
%
% The carrier functions are triangle modulated to generate rising and falling
% amplituded. The modulation frequency is  set to:
%
% $f_m = 0.01Hz$
%
% Which generates a stimulus with 320 periods where 160 periods feeds a rising
% and falling record each multiplied with maximum fieldstrength amplitude:
%
% $m(t) = H_{max} \cdot tri(t) = H_{max} \cdot tri(2(t-t_0)f_m)$
%
% $t_0 = \frac{1}{2f_m}$
% 
% So the Hx- and Hy-field stimulus is described by:
%
% $H_x(t) = m(t) \cdot c_1(t)$
%
% $H_y(t) = m(t) \cdot c_1(t)$
%
% The stimulus amplitude depending on the phase in polar coordinates can be
% displayed for both parts by:
%
% $H_{x,y}(\phi) = |H_{x,y}(\phi)| \cdot e^{j\phi} = m(t) \cdot e^{j\phi(t)}$
%
% Where a rising spiral runs from center outwards for:
%
% $0 < t < t_0$
%
% And a falling spiral of amplitudes from outwards to center for:
%
% $t_0 < t < \frac{1}{f_m}$
%
% <html>
% <img src="images/tdk_magnetic_stimulus.svg" height=650>
% </html>
%
%
%% Cosinuns Bridge Output
%
% <html>
% <img src="images/tdk_cosinus_bridge.svg" height=650>
% </html>
%
%
%% Sinus Bridge Output
%
% <html>
% <img src="images/tdk_sinus_bridge.svg" height=650>
% </html>
%